<a href="https://colab.research.google.com/github/shv-om/Cryptology/blob/main/DES_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conversion to Binary

In [ ]:
def conbin(msg):
  newstream = []
  for m in msg:
    b = format(int(m, 16), '04b')
    newstream.append(b.replace('0b', ''))
  
  return ''.join(newstream)

In [ ]:
msgstream = list(conbin('0123456789abcdef'))
print(msgstream)
print(len(msgstream))

['0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '0', '1', '1', '1', '1', '0', '0', '0', '1', '0', '0', '1', '1', '0', '1', '0', '1', '0', '1', '1', '1', '1', '0', '0', '1', '1', '0', '1', '1', '1', '1', '0', '1', '1', '1', '1']
64


# Permutation

In [107]:
def calc_permutation(stream, pmatrix):
  pmshape = pmatrix.shape
  pmsize = pmatrix.size

  newstream = np.empty(pmshape, str)
  
  for i in range(pmshape[0]):
    for j in range(pmshape[1]):
      # print(i, j, '-->', pmatrix[i][j]-1)
      newstream[i][j] = stream[pmatrix[i][j]-1]

  return ''.join(newstream.reshape(pmsize))

In [ ]:
# Splitting stream into Left and Right stream
def split_left_right(stream):
  left_part = stream[:len(stream)//2]
  right_part = stream[len(stream)//2:]

  return ''.join(left_part), ''.join(right_part)

# Initial Permutation

In [ ]:
import numpy as np

IP = np.array([[58, 50, 42, 34, 26, 18, 10, 2],
              [60, 52, 44, 32, 28, 20, 12, 4],
              [62, 54, 46, 38, 30, 22, 14, 6],
              [64, 56, 48, 40, 32, 24, 16, 8],
              [57, 49, 41, 33, 25, 17, 9, 1],
              [59, 51, 43, 35, 27, 19, 11, 3],
              [61, 53, 45, 37, 29, 21, 13, 5],
              [63, 55, 47, 39, 31, 23, 15, 7]])

IP

array([[58, 50, 42, 34, 26, 18, 10,  2],
       [60, 52, 44, 32, 28, 20, 12,  4],
       [62, 54, 46, 38, 30, 22, 14,  6],
       [64, 56, 48, 40, 32, 24, 16,  8],
       [57, 49, 41, 33, 25, 17,  9,  1],
       [59, 51, 43, 35, 27, 19, 11,  3],
       [61, 53, 45, 37, 29, 21, 13,  5],
       [63, 55, 47, 39, 31, 23, 15,  7]])

In [108]:
# Initial Permutation
initstream = calc_permutation(msgstream, IP)
initstream

'1100110000010000110011001111111111110000101010101111000010101010'

In [ ]:
MsgLeft, MsgRight = split_left_right(initstream)
MsgLeft, MsgRight

('11001100000100001100110011111111', '11110000101010101111000010101010')

# Key Generation

In [ ]:
# Key circular left shift
def key_left_circular_shift(stream, times):
    for i in range(times):
      stream = stream[1:] + stream[0]
    
    return stream

In [ ]:
keystream = list(conbin('1234abfce5872cb9'))
print(keystream)
print(len(keystream))

['0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '0', '0', '1', '0', '1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '0', '1', '0', '1', '1', '0', '0', '0', '0', '1', '1', '1', '0', '0', '1', '0', '1', '1', '0', '0', '1', '0', '1', '1', '1', '0', '0', '1']
64


In [ ]:
pc1 = np.array([[57, 49, 41, 33, 25, 17, 9],
                [1, 58, 50, 42, 34, 26, 18],
                [10, 2, 59, 51, 43, 35, 27],
                [19, 11, 3, 60, 52, 44, 36],
                [63, 55, 47, 39, 31, 23, 15],
                [7, 62, 54, 46, 38, 30, 22],
                [14, 6, 61, 53, 45, 37, 29],
                [21, 13, 5, 28, 20, 12, 4]])

pc1

array([[57, 49, 41, 33, 25, 17,  9],
       [ 1, 58, 50, 42, 34, 26, 18],
       [10,  2, 59, 51, 43, 35, 27],
       [19, 11,  3, 60, 52, 44, 36],
       [63, 55, 47, 39, 31, 23, 15],
       [ 7, 62, 54, 46, 38, 30, 22],
       [14,  6, 61, 53, 45, 37, 29],
       [21, 13,  5, 28, 20, 12,  4]])

In [ ]:
pc2 = np.array([[14, 17, 11, 24, 1, 5],
                [3, 28, 15, 6, 21, 10],
                [23, 19, 12, 4, 26, 8],
                [16, 7, 27, 20, 13, 2],
                [41, 52, 31, 37, 47, 55],
                [30, 40, 51, 45, 33, 48],
                [44, 49, 39, 56, 34, 53],
                [46, 42, 50, 36, 29, 32]])

pc2

array([[14, 17, 11, 24,  1,  5],
       [ 3, 28, 15,  6, 21, 10],
       [23, 19, 12,  4, 26,  8],
       [16,  7, 27, 20, 13,  2],
       [41, 52, 31, 37, 47, 55],
       [30, 40, 51, 45, 33, 48],
       [44, 49, 39, 56, 34, 53],
       [46, 42, 50, 36, 29, 32]])

In [109]:
key_permuted = calc_permutation(keystream, pc1)
key_permuted

'10111100000110001101111010000010010101111010110011001011'

In [110]:
# Splitting keystream into left and right part
KeyLeft, KeyRight = split_left_right(key_permuted)
KeyLeft, KeyRight

('1011110000011000110111101000', '0010010101111010110011001011')

In [111]:
# Creating 16 keys by Left shift
key_pairs = []

tempkeypair = KeyLeft, KeyRight

for i in range(1, 17):
  if i in [1, 2, 9, 16]:
    tempkeypair = key_left_circular_shift(tempkeypair[0], 1), key_left_circular_shift(tempkeypair[1], 1)
  else:
    tempkeypair = key_left_circular_shift(tempkeypair[0], 2), key_left_circular_shift(tempkeypair[1], 2)
  
  key_pairs.append(tempkeypair)

key_pairs


[('0111100000110001101111010001', '0100101011110101100110010110'),
 ('1111000001100011011110100010', '1001010111101011001100101100'),
 ('1100000110001101111010001011', '0101011110101100110010110010'),
 ('0000011000110111101000101111', '0101111010110011001011001001'),
 ('0001100011011110100010111100', '0111101011001100101100100101'),
 ('0110001101111010001011110000', '1110101100110010110010010101'),
 ('1000110111101000101111000001', '1010110011001011001001010111'),
 ('0011011110100010111100000110', '1011001100101100100101011110'),
 ('0110111101000101111000001100', '0110011001011001001010111101'),
 ('1011110100010111100000110001', '1001100101100100101011110101'),
 ('1111010001011110000011000110', '0110010110010010101111010110'),
 ('1101000101111000001100011011', '1001011001001010111101011001'),
 ('0100010111100000110001101111', '0101100100101011110101100110'),
 ('0001011110000011000110111101', '0110010010101111010110011001'),
 ('0101111000001100011011110100', '100100101011110101100110010

In [112]:
list_of_keys = []

for i in range(16):
  temp_key = key_pairs[i][0] + key_pairs[i][1]
  list_of_keys.append(calc_permutation(temp_key, pc2))

list_of_keys


['011101110010011100100101010101110111111000010000',
 '001010101011110100101101100110001001101011000111',
 '110010010010010001101011110101101100011010110101',
 '111000011100111010111000000110110010111111001001',
 '110101001011101110000010101110101111000100010001',
 '001100101011111001010011011000110110011100100110',
 '011011010111010001000110111111000010100110001010',
 '011000101100010111011100111001000101001001011111',
 '110001100101010011110001111010111000110111000000',
 '110111111100101101100000010010001110011100011111',
 '100010101111001110001011011111110101010010001100',
 '001110010001011101001111110010000101000111101011',
 '011000010101100011001001100001101111101000101101',
 '000100011110100111110100111100100001111111110000',
 '100101000110110110010011100110011000101100111011',
 '010011100110101100000110101001010100011111101100']

In [ ]:
FP = np.array([[40, 8, 48, 16, 56, 24, 64, 32],
              [39, 7, 47, 15, 55, 23, 63, 31],
              [38, 6, 46, 14, 54, 22, 62, 30],
              [37, 5, 45, 13, 53, 21, 61, 29],
              [36, 4, 44, 12, 52, 20, 60, 28],
              [35, 3, 43, 11, 51, 19, 59, 27],
              [34, 2, 42, 10, 50, 18, 58, 26],
              [33, 1, 41, 9, 49, 17, 57, 25]])